### ISSUE TITLE
Add a VCS-independent way of determining the root dir

### ISSUE THREAD

**Issue by sqs** [sourcegraph/go-vcs#9]
Given a directory, it'd be nice to be able to find the VCS root dir in that dir's ancestors (including itself) for both Git and hg.

Add a new function/method?

**Comment by shurcooL** [comment]
This is related to shurcooL/go#18.

**Comment by shurcooL** [comment]
I'll close this because I think this functionality is outside the scope of this library. go-vcs is about manipulating and inspecting VCS repositories, not finding and discovering them.

For directories that are in a GOPATH workspace, there is existing functionality in external standard library. One can use [`golang.org/x/tools/go/vcs.FromDir`](https://godoc.org/golang.org/x/tools/go/vcs#FromDir).

```Go
// FromDir inspects dir and its parents to determine the
// version control system and code repository to use.
// On return, root is the import path
// corresponding to the root of the repository.
func FromDir(dir, srcRoot string) (vcs *Cmd, root string, err error) {
```

For more specialized uses cases, a dedicated unexported helper can be written. For example, see https://github.com/sourcegraph/go-vcs/commit/f16adad7827edda5abb035199dafb4478c4a3af2.
